### ISSUE TITLE
getting the best sql with filters

### ISSUE THREAD

**Issue by ahmettaha** [jcachat/EntityFramework.DynamicFilters#53] opened 2015-12-22 15:02 UTC
Hello,

I'm trying to use your library. I have a concern with the generated sql. When I try your code the isDeleted filter produces a sql like below.
my filter is below
 modelBuilder.Filter("IsDeleted", (IEntitySoftDelete d) => d.IsDeleted, false);
```
SELECT
    [Extent1].[Id] AS [Id],
    [Extent1].[IsDeleted] AS [IsDeleted],
    [Extent1].[Name] AS [Name],
    [Extent1].[Nav1_Id] AS [Nav1_Id],
    [Extent1].[Nav2_Id] AS [Nav2_Id],
    [Extent1].[Nav3_Id] AS [Nav3_Id]
    FROM [dbo].[EntityAs] AS [Extent1]
    WHERE (
    		([Extent1].[IsDeleted] = @DynamicFilterParam_1) 
    	 OR (@DynamicFilterParam_2 IS NOT NULL)
    ) AND (N'ahmet' = [Extent1].[Name])

-- DynamicFilterParam_1: 'null' (Type = Boolean, IsNullable = false)
-- DynamicFilterParam_2: 'null' (Type = Boolean)
-- Executing at 12/22/2015 2:54:12 PM +00:00
-- Completed in 15 ms with result: SqlDataReader
```

However, I'm expexting a sql like below
```
SELECT
    [Extent1].[Id] AS [Id],
    [Extent1].[IsDeleted] AS [IsDeleted],
    [Extent1].[Name] AS [Name],
    [Extent1].[Nav1_Id] AS [Nav1_Id],
    [Extent1].[Nav2_Id] AS [Nav2_Id],
    [Extent1].[Nav3_Id] AS [Nav3_Id]
    FROM [dbo].[EntityAs] AS [Extent1]
    WHERE (
    		([Extent1].[IsDeleted] = @DynamicFilterParam_1)
    ) AND (N'ahmet' = [Extent1].[Name])
```
Where is that extra part coming from and why is it there?

Also, I couldnt get a good sql when I tried with a DateTime? type property. I get a sql like below
my filter is below
 modelBuilder.Filter("DeleteTime", (IMsSqlEntity subscription) => (subscription.DeleteTime == null));
```
SELECT TOP (2)
    [Extent1].[Id] AS [Id],
    [Extent1].[Name] AS [Name],
    [Extent1].[InsertTime] AS [InsertTime],
    [Extent1].[DeleteTime] AS [DeleteTime]
    FROM [dbo].[MsSqlSample] AS [Extent1]
    WHERE (([Extent1].[DeleteTime] IS NULL) OR (@DynamicFilterParam_1 IS NOT NULL)) AND ([Extent1].[Id] = @p0)
-- DynamicFilterParam_1: 'null' (Type = Boolean)
-- p0: 'd0771ea6-bca8-e511-9cdd-000c29a3f59d' (Type = Guid)
-- Executing at 12/22/2015 2:59:51 PM +00:00
-- Completed in 12 ms with result: SqlDataReader
```

where is this  (@DynamicFilterParam_1 IS NOT NULL) part coming from? How do I remove it?

**Comment by jcachat** [comment] 2015-12-22 15:24
The "@param is not null" clause is there in order to allow us to temporarily disable the filter.  EF gives us only 1 chance to define exactly how that query is formed so there is no other way to modify it (in case we want to disable it later) once it's been compiled.  So we have to compile that check into the query all the time.  I had the same concern and tried everything I could to avoid having to do that but there was no way to avoid it.

However, that condition is only checking a parameter (not a column in the table) so while it does make the query larger and uglier, it doesn't affect the query performance at all.  Compare it in SQL Profiler (or in Query Analyzer with query stats turned on) and you should be able to confirm that.

**Comment by ahmettaha** [comment] 2015-12-22 15:36
is it possible to disable to feature completely? I'm never going to need it.

**Comment by jcachat** [comment] 2015-12-22 15:43
Sorry, there isn't an option to do that.

**Comment by ahmettaha** [comment] 2015-12-22 15:45
thank you for the great libary. I have one small question. Do you have any suggestions to make it softdelete with the dbcontext.Remove command?

**Comment by jcachat** [comment] 2015-12-22 16:08
Sure, that's actually pretty easy with the filtering.  There is an example for the filter on the main page here (using an ISoftDelete interface) so create your filter & interface something like that.

To catch the record deletes and switch them into soft deletes, do this:

In your custom DbContext class, override SaveChanges() like this:
```
public override int SaveChanges()
{
    foreach (var dbEntityEntry in ChangeTracker.Entries<ISoftDeletable>().Where(e => e.State == EntityState.Deleted))
    {
        //  We are soft deleting these items so change the state to unchanged and then update the IsDeleted flag.
        dbEntityEntry.State = EntityState.Unchanged;
        dbEntityEntry.Entity.IsDeleted = true;
    }

    return base.SaveChanges();
}
```

That just intercepts any deletes on ISoftDelete entities immediately before they are written to the DB.  It changes them from a Delete to an Update and sets the IsDeleted flag to true (setting to Unchanged and then changing the property triggers it to be an update).  This is the exact method I use in my own system.

And this is a great reason to keep the Disable filter option available.  If you are soft deleting and ever want to provide the option for users to see what's "in the trash", you just temporarily disable that filter (and only for your local DbContext scope so doesn't affect any other queries) and you can query them when you need to.

**Comment by ahmettaha** [comment] 2015-12-22 16:09
thank you very much

**Comment by jcachat** [comment] 2015-12-22 16:30
This may not apply to your situation, but I should also mention that intercepting the deletes like that could still cause child collection relationships to be lost or 1-to-many child entities to be cascade deleted.  That will depend on the FK relationships which EF will follow in order to maintain the integrity of the entity that is being deleted.  The code above changes the main entity to not be deleted, but at that point, EF has already figured out what it wants to do with any other related entities.

So you may need to add some more logic in there to handle these situations.  A call to "dbEntityEntry.Reload();" before you set the IsDeleted flag *MIGHT* do the trick but I have't verified that (I don't think that will hydrate the child collections).  This is actually an issue I need to track down in my own system - it's just a low impact priority for us atm.

**Comment by ahmettaha** [comment] 2015-12-22 17:37
Can you give me an example when this could happen? I couldnt get it to reproduce this situation

**Comment by jcachat** [comment] 2015-12-22 17:55
Here are the 2 situations:

```
public class Parent
{
    public int ID { get; set; }

    public ICollection<OneToManyChild> OneToManyChildren { get; set; }
    public ICollection<ManyToManyChild> ManyToManyChildren { get; set; }
}

public class OneToManyChild
{
    public int ID { get; set; }

    public int ParentID { get; set; }
    public Parent Parent { get; set; }
}

public class ManyToManyChild
{
    public int ID { get; set; }

    public ICollection<Parent> Parents { get; set; }
}
```

If you delete a "Parent" entity when those 2 child collections are loaded, EF will do this:
1) It will mark all of the "OneToManyChild" entities to also be deleted.
2) It will remove the records in the many-to-many table that connect all of the Parent records being deleted to the "ManyToManyChild" records.
You are changing "Parent" to not actually be deleted but EF has already decided to take those steps above.  So the extra logic is required to tell EF not to do that stuff.

If you don't have those collections loaded, EF should leave them alone since it isn't aware of them unless they are loaded into the context.  And since  you are changing Parent to use SoftDelete, SQL Server will also leave them alone since it's not actually deleting the record (so will not cascade delete).

I should have specified that before - it's just an issue if you have those collections loaded into the context.

And now that I think about it, that's probably going to be the solution to my problem as well.  I'm sure where I'm experiencing that issue, it's just a result of someone "including" some child collections when they should not be.

**Comment by ahmettaha** [comment] 2015-12-22 18:19
with the code below, it would soft delete the parent and hard delete the child?
```
var parent = dbcontext.Parents.Find(id);
var child = dbcontext.OneToManyChilds.Find(id);
dbcontext.Parents.Remove(parent);
```

but if I just do below, it would softdelete the parent only?
```
var parent = dbcontext.Parents.Find(id);
dbcontext.Parents.Remove(parent);
```

**Comment by jcachat** [comment] 2015-12-22 18:21
Yes

**Comment by ahmettaha** [comment] 2015-12-22 20:13
I'm sorry for my ignorance but why do you have 

```
public int ParentID { get; set; }
```

isn't it implicitly defined and used on the table anyways?

**Comment by jcachat** [comment] 2015-12-22 20:45
It is.  I just tend to be explicit about it.  And if you load the entity without including the parent navigation property, you have access to the ID right there.

**Comment by ahmettaha** [comment] 2015-12-22 21:00
Thank you very much. Your contribution to entiy framework is great. 

I think i found another flaw in the soft delete pattern. 

if i delete the parent, it soft deletes the parent entity which is great.  My concern is it also removes the parentid on the onetomany table. It doesnt soft delete or hard delete it. It just breaks the relation by setting it to null in the child. Is there a way to keep the parentid and make it soft delete on the onetomanychild

**Comment by ahmettaha** [comment] 2015-12-22 23:28
I got it figured out with a command interceptor by the way. Thank you very much.

**Comment by ahmettaha** [comment] 2016-04-10 16:57
Hello,
It has been a while since we discussed this issue. However, I have a new discovery. Some execution plans do not take affect if the Delete condition is written like below

    ([Extent1].[IsDeleted] = @DynamicFilterParam_1)  OR (@DynamicFilterParam_2 IS NOT NULL)

However, the index got applied if I changed the url to ([Extent1].[IsDeleted] is null.

Is it possible to at least tie this feature to an app setting, or some other field? I know that this feature is used to globally turn on/off the filters, however for conditions like mine, I need to have a query without the extra OR.

Thanks.

**Comment by jcachat** [comment] 2016-04-11 13:59
The condition on @DynamicFilterParam_2 is done directly against a parameter - not against a table value.  So it should not affect the query plan in any way.  The only index usage that should be done would be against the IsDelete column.  Maybe you're hitting a situation I did not, but I did extensive testing on this and never found it to cause any change in index usage.  And I have never seen it cause a problem in my own use of this library in a high volume production system.

Can you try rebuilding your indexes and see if that changes the behavior?  It could be an issue with index statistics being out of date and the query could have been compiled incorrectly.

I would not want to disable this globally throughout the application (via app.config).  But, I would consider making a "per filter" command to disable it.  Something similar to how a filter can be enabled or disabled - a new command that turns it off completely just for that filter.

If this is reproducible in a small example you can share, that would be helpful too.

**Comment by ahmettaha** [comment] 2016-04-11 14:10
It was working for me too. Then one day, i have changed the column order in an index and the the query stopped using the index. However, when o changed it to a direct is not null approach, it was used again. It may have been a very rare issue but i rather have an option per filter at worst. 

Thank you.

**Comment by jcachat** [comment] 2016-04-11 14:26
Is your IsDelete column nullable?  Shouldn't that be a "not null" bit column?  What happens if you take the exact query created by DynamicFilters and just remove the "OR (@DynamicFilterParam_2 IS NOT NULL)" part?  If I did disable this functionality, that is the query that would be created so this is what you should test against.

How is the index defined that includes the IsDelete column and what is the full query that is being executed?

**Comment by ahmettaha** [comment] 2016-04-11 15:00
Hello,

Actually I hve a nullable DeleteTime field. It is is null, then the record is active. if it is not null then it is deleted.

yes, that query works for me. I had tested it manually.



.

**Comment by jcachat** [comment] 2016-04-11 15:10
Ok, that will work fine.  But, you said the query conditions are:
```
([Extent1].[IsDeleted] = @DynamicFilterParam_1)  OR (@DynamicFilterParam_2 IS NOT NULL)
```
Which is not correct if the field is nullable and if you have your filter configured to check for a null value.  It should be producing SQL like this: 
```
([Extent1].[IsDeleted] IS NULL)  OR (@DynamicFilterParam_2 IS NOT NULL)
```

I'm trying to make sure I understand exactly what's going on here and I don't think I have a clear picture of that yet.

Please post (or email to jcachat12 at gmail.com) your model, the filter, the full sql query that is being generated, and the applicable index(es)

**Comment by ahmettaha** [comment] 2016-04-11 15:16
oh I see. I think you are confused, becuase of my very first message. That model is changed. Now, it is not IsDeleted anymore. It is nullable delete time. and the generated sql is something like below.

([Extent1].[DeleteTime] IS NULL)  OR (@DynamicFilterParam_2 IS NOT NULL)


.

**Comment by jcachat** [comment] 2016-04-11 15:24
Ok, that makes more sense now.

But, I still have 1 concern.  You said: "It was working for me too. Then one day, i have changed the column order in an index and the the query stopped using the index."

Did you make that change at the same time you changed this from IsDeleted to the nullable DeleteTime?

I really want to understand the full picture and would like to be able to reproduce the problem so I can check to see if this change you are requesting will even solve your problem.  It will take a couple hours of work so I want to make sure it will be worthwhile.

** Please post (or email to jcachat12 at gmail.com) your model, the filter, the full sql query that is being generated, and the applicable index(es).

**Comment by ahmettaha** [comment] 2016-04-17 20:58
I had sent you a direct email. I just have more examples. I have sent them to you also. 

Thanks.



.

**Comment by jcachat** [comment] 2016-04-21 02:23
I was able to reproduce the exact same problem with the information you sent me.  It really seems like a bug in the SQL Server query optimizer, but that's not something I can fix.  So I just pushed out an update (also to NuGet) that now does this:

If the filter is enabled, when the sql is intercepted, I am manually removing the "OR 
  (@DynamicFilterParam_1 IS NOT NULL)" clause from the sql statement.  So this will result in the sql statement exactly as you were requesting.

If the filter is DISABLED, it will still include that condition as that is the only way to cause the filter to not actually be evaluated.  Removing the rest of the filter condition would not be possible since we have no way to be able to tell exactly where it is (since it could be quite complex).  I am only able to remove the part specified above because it's very simple and in a predictable form.

Give that a try and let me know if that solves your problem or if you have any issues.

**Comment by ahmettaha** [comment] 2016-04-21 07:08
Hello,

Doing an adjustment in the sql string is fine, but I feel like it is something that may break, if entity framework updates. I think I would be more comfortable if we can disable adding this clause all together. I know you had said that the queries are cached, and you can not add this clause on runtime later if needed, but I think it is acceptable. It can be decided on the first execution wheather to include it or not. As far as I have seen, because this issue hasnt been brought before I did, no one else is going to be affacted by this with a backward compability problem.



.

**Comment by jcachat** [comment] 2016-04-21 15:21
I completely agree about changing the sql string - and that's why I have not wanted to do this before.

However, in this case I don't think there was a choice and it turned out to be a very straightforward modification (which I also tested against Oracle and MySql).

The problem with making the change you are requesting is:
1) It will require making a code change in your application to specifically turn off the filter disabling feature.
2) It would require someone actually spotting the poorly performing query/missing index recommendation to even know that something needs to be done proactively.  It's great that you found this issue but it's been my experience that 90% of developers do not even bother to look at the query performance in any way unless they are specifically working a performance bug that has been reported to them.  So other users may be experiencing this issue and not even know it.
3) Turning off this feature is not feasible for someone who is having this issue and also needs to be able to disable the filter.

The change I made will solve the problem without requiring any application changes and without sacrificing any functionality.

I'm going to leave this change as it is because I feel it is a better overall solution for all users.  But if it does cause any problems, I will revisit it and can add the option you are asking for.

**Comment by ahmettaha** [comment] 2016-04-21 17:06
ok. so do I need to change anyting on my code to enable this feature? Or is just updating enough?



.

**Comment by jcachat** [comment] 2016-04-21 17:10
Just update the library.

**Comment by jcachat** [comment] 2016-04-24 16:47
I added these 2 methods:
```
modelBuilder.PreventDisabledFilterConditions("IsDeleted");  // disable a single filter
modelBuilder.PreventAllDisabledFilterConditions();          // disable all filters defined up to calling this method
```
that you can use to completely turn off the enable/disable filter functionality.  It must be done in OnModelCreating.  And once done, cannot be undone and will be in effect during the entire application life cycle.

If you use PreventAllDisabledFilterConditions(), make sure to call it after you have defined all of your filters (so at the very end of OnModelCreating).

I would still appreciate your help in figuring out why the sql string replacement is not working for you.  If there is a problem there, I would like to correct it.

**Closed** 2016-06-12 15:28 UTC
