### ISSUE TITLE
New Feature - Add Linq/Lambda support

### ISSUE THREAD

**Issue by adrianotrentim** [jcachat/EntityFramework.DynamicFilters#7] opened 2014-12-10 17:44 UTC
Hello friend,
Your article is sensational.
But, I have a need here, and could not identify how can I do.
Here's an example:
modelBuilder.Filter ("MyEntity" (MyEntity p) =>              {                  var myArray = new [] {1,2,5,8,20,30};
                 return myArray.Contains (p.MyEntityID);                               });
Is there any way to do this?
Consider that myArray can be dynamic.

**Comment by gab1990** [comment] 2015-01-15 09:41
Hello and thank you for your work. 

I also need to have a "In" condition with a list of values instead of only a "Equals". It would be great if you could add this possibility in your solution.

Like I need it very soon, I'm looking for a temporary solution to solve this use case. I'm using a very simple dynamic filters solution based on your code, and for now the only solution I found is to create a sql parameter and add a ".Or" to the DbExpression for each values of my list...

Then "where MyentityId In(@MyentityIdParameter1, @MyentityIdParameter2, @MyentityIdParameter3, ...)" is added to the query.

Do you have another idea? @adrianotrentim, can you share the solution you found ?

Thanks!

**Comment by adrianotrentim** [comment] 2015-01-15 11:49
Hello,

 

I have not stopped to implemente any change in this solution.

 

For now, I’m using na old solution mine, based directly on DbSet property.

 

Att,

 

 

 


 


Adriano Trentim Augusto 






Diretor


Telefones: (16) 3011-3181 - (16) 99749-9099


E-mail:  <mailto:adriano@divsoft.com.br> adriano@divsoft.com.br


WebSite:  <http://www.divsoft.com.br/> http://www.divsoft.com.br/


 
 
 
 

 

De: gab1990 [mailto:notifications@github.com] 
Enviada em: quinta-feira, 15 de janeiro de 2015 07:41
Para: jcachat/EntityFramework.DynamicFilters
Cc: adrianotrentim
Assunto: Re: [EntityFramework.DynamicFilters] New Feature - Add Linq/Lambda support (#7)

 

Hello and thank you for your work. 

I also need to have a "In" condition with a list of values instead of only a "Equals". It would be great if you could add this possibility in your solution.

Like I need it very soon, I'm looking for a temporary solution to solve this use case. I'm using a very simple dynamic filters solution based on your code, and for now the only solution I found is to create a sql parameter and add a ".Or" to the DbExpression for each values of my list...

Then "where MyentityId In(@MyentityIdParameter1, @MyentityIdParameter2, @MyentityIdParameter3, ...)" is added to the query.

Do you have another idea? @adrianotrentim <https://github.com/adrianotrentim> , can you share the solution you found ?

Thanks!

**Comment by jcachat** [comment] 2015-01-15 22:19
I recently pushed changes that allow the creation of linq filters.  See here for more info: https://github.com/jcachat/EntityFramework.DynamicFilters/issues/9#issuecomment-68494601

But, it does not currently support Contains().  I have been working on that but have hit some complications:
1) The DbInExpression which is used to construct this query in EF requires the list of values at the time the query is built (which only happens once - when it is first compiled).  So if the list of values changes in between query executions (i.e. dynamically - which is the point of this library), there is no opportunity to change the values or the number of items in the list.
2) And more importantly, DbInExpression only accepts CONSTANT values.  There is no way for me to even give it DbParameterReferences which is needed in order for EF to generate sql parameters for me to intercept and replace.

I have not given up on this yet.  But it's not going to be an easy thing to support.  And it will probably require manually modifying the sql statement before it is executed.  Which could get ugly and I would like to avoid having to resort to that...

In the mean time, you can use the linq support if the number of items in your list will not change.  But you will have to do that by creating a linq expression that is a series of "or" conditions against each value in your list.  I believe that will be optimized by EF into an "In" condition in the sql - just like how you've already done it.

**Comment by jcachat** [comment] 2015-01-18 18:19
I just pushed changes (and updated the NuGet package) to support Contains() in the linq filter.  It's not pretty, but it seems to work.   I'll update the docs shortly to show examples of the linq filters.  But, for now, this is roughly what a Contains() filter would look like:

    var values = new List<int> { 1, 2, 3, 4, 5 };
    modelBuilder.Filter("BlogContainsTest", (BlogEntry b, List<int> valueList) => valueList.Contains(b.IntValue), () => values);

It requires an IEnumerable<T> list (it will not support the non-generic IEnumerable or ArrayList) but should support any simple datatype as T.

**Comment by jcachat** [comment] 2015-01-18 23:21
I should also mention that if you are logging the queries to the console, you will see the "Contains()" condition show as an "=" condition against a single parameter value.  This is because EF is logging the query to the console BEFORE I do some funny business on it.  So don't be alarmed.  If using SQL Server, use SQL Profiler to see the real query.

What's happening here is that in order to make the collection values dynamic, I create the query as an '=' condition against 1 parameter.  Then when I intercept it, I see the parameter is a collection and I change the query from an '=' to an 'in' by modifying the sql command that EF generated.  That single parameter is set to the value of the first item in the collection and the remaining items are appended directly to the sql 'in' clause.  Like I said, it's not pretty.  But it was the only way I could find to be able to provide the collection values dynamically.

**Comment by gab1990** [comment] 2015-01-19 21:35
Thank you very much for the solution, it seems to work well ! :)

**Comment by adrianotrentim** [comment] 2015-01-21 12:55
Tks

 

 

 


 


Adriano Trentim Augusto 






Diretor


Telefones: (16) 3011-3181 - (16) 99749-9099


E-mail:  <mailto:adriano@divsoft.com.br> adriano@divsoft.com.br


WebSite:  <http://www.divsoft.com.br/> http://www.divsoft.com.br/


 
 
 
 

 

De: jcachat [mailto:notifications@github.com] 
Enviada em: domingo, 18 de janeiro de 2015 16:20
Para: jcachat/EntityFramework.DynamicFilters
Cc: adrianotrentim
Assunto: Re: [EntityFramework.DynamicFilters] New Feature - Add Linq/Lambda support (#7)

 

I just pushed changes (and updated the NuGet package) to support Contains() in the linq filter. It's not pretty, but it seems to work. I'll update the docs shortly to show examples of the linq filters. But, for now, this is roughly what a Contains() filter would look like:

var values = new List<int> { 1, 2, 3, 4, 5 };
modelBuilder.Filter("BlogContainsTest", (BlogEntry b, List<int> valueList) => valueList.Contains(b.IntValue), () => values);

It requires an IEnumerable list (it will not support the non-generic IEnumerable or ArrayList) but should support any simple datatype as T.

**Comment by adrianotrentim** [comment] 2015-01-21 12:58
It is possible, this new functionality out instead of returning a list as in the example, pass the parameter "values" one function that returns a list, as shown below?

 

 

var values = new List<int> { 1, 2, 3, 4, 5 };
modelBuilder.Filter("BlogContainsTest", (BlogEntry b, List<int> valueList) => valueList.Contains(b.IntValue), () => {
        var valueList = new List<int> { 1, 2, 3, 4, 5 };
 
        return valueList;
});

 

 

 


 


Adriano Trentim Augusto 






Diretor


Telefones: (16) 3011-3181 - (16) 99749-9099


E-mail:  <mailto:adriano@divsoft.com.br> adriano@divsoft.com.br


WebSite:  <http://www.divsoft.com.br/> http://www.divsoft.com.br/


 
 
 
 

 

De: jcachat [mailto:notifications@github.com] 
Enviada em: domingo, 18 de janeiro de 2015 16:20
Para: jcachat/EntityFramework.DynamicFilters
Cc: adrianotrentim
Assunto: Re: [EntityFramework.DynamicFilters] New Feature - Add Linq/Lambda support (#7)

 

I just pushed changes (and updated the NuGet package) to support Contains() in the linq filter. It's not pretty, but it seems to work. I'll update the docs shortly to show examples of the linq filters. But, for now, this is roughly what a Contains() filter would look like:

var values = new List<int> { 1, 2, 3, 4, 5 };
modelBuilder.Filter("BlogContainsTest", (BlogEntry b, List<int> valueList) => valueList.Contains(b.IntValue), () => values);

It requires an IEnumerable list (it will not support the non-generic IEnumerable or ArrayList) but should support any simple datatype as T.

**Comment by jcachat** [comment] 2015-01-21 13:48
Yes, that works.  That delegate is evaluated/executed to obtain the result so it can contain code and return a value.

**Comment by adrianotrentim** [comment] 2015-01-21 14:05
Tks

 

 

 


 


Adriano Trentim Augusto 






Diretor


Telefones: (16) 3011-3181 - (16) 99749-9099


E-mail:  <mailto:adriano@divsoft.com.br> adriano@divsoft.com.br


WebSite:  <http://www.divsoft.com.br/> http://www.divsoft.com.br/


 
 
 
 

 

De: jcachat [mailto:notifications@github.com] 
Enviada em: quarta-feira, 21 de janeiro de 2015 11:48
Para: jcachat/EntityFramework.DynamicFilters
Cc: adrianotrentim
Assunto: Re: [EntityFramework.DynamicFilters] New Feature - Add Linq/Lambda support (#7)

 

Yes, that works. That delegate is evaluated/executed to obtain the result so it can contain code and return a value.

**Comment by adrianotrentim** [comment] 2015-01-22 17:09
Hello,

 

Using the library, found some errors using the constains function, did some simple tests, and gives this error: "length can not be less than zero: Parameter name: length".

 

StackTrace:

 

   em System.String.Substring(Int32 startIndex, Int32 length)

   em EntityFramework.DynamicFilters.DynamicFilterExtensions.SetParameterList(IEnumerable paramValueCollection, DbParameter param, DbCommand command)

   em EntityFramework.DynamicFilters.DynamicFilterExtensions.SetSqlParameters(DbContext context, DbCommand command)

   em EntityFramework.DynamicFilters.DynamicFilterCommandInterceptor.SetDynamicFilterParameterValues(DbCommand command, DbContext context)

   em EntityFramework.DynamicFilters.DynamicFilterCommandInterceptor.ReaderExecuting(DbCommand command, DbCommandInterceptionContext`1 interceptionContext)

   em System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__d(IDbCommandInterceptor i, DbCommand t, DbCommandInterceptionContext`1 c)

   em System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)

   em System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)

   em System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)

   em System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)

   em System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)

 

Here is my code, to filter configuration

 

 

modelBuilder.Filter(GetType().Name, (Menu query, List<Guid> values) =>

            values.Contains(query.IdMenu),

            () =>

            {

                return new List<Guid>

                {

                    Guid.Parse("E63C3CC1-598A-E211-A120-00163EA5B928"),

                    Guid.Parse("3208EAF0-5B8A-E211-A120-00163EA5B928"),

                    Guid.Parse("A0D6CA1A-E58B-E211-A120-00163EA5B928"),

                    Guid.Parse("58FD6D5F-E58B-E211-A120-00163EA5B928"),

                    Guid.Parse("7B471832-AB8D-E211-A120-00163EA5B928"),

                    Guid.Parse("385D9D3B-AB8D-E211-A120-00163EA5B928"),

                    Guid.Parse("AA607A4B-AB8D-E211-A120-00163EA5B928"),

                    Guid.Parse("B9358955-8543-E211-BE71-889FFA5DCE70"),

                    Guid.Parse("BA358955-8543-E211-BE71-889FFA5DCE70"),

                    Guid.Parse("BB358955-8543-E211-BE71-889FFA5DCE70"),

                    Guid.Parse("BC358955-8543-E211-BE71-889FFA5DCE70"),

                    Guid.Parse("BD358955-8543-E211-BE71-889FFA5DCE70")

                };

            });

 

 

Any ideia?

 

Att,

 

 

 

 


 


Adriano Trentim Augusto 






Diretor


Telefones: (16) 3011-3181 - (16) 99749-9099


E-mail:  <mailto:adriano@divsoft.com.br> adriano@divsoft.com.br


WebSite:  <http://www.divsoft.com.br/> http://www.divsoft.com.br/


 
 
 
 

 

De: jcachat [mailto:notifications@github.com] 
Enviada em: quarta-feira, 21 de janeiro de 2015 11:48
Para: jcachat/EntityFramework.DynamicFilters
Cc: adrianotrentim
Assunto: Re: [EntityFramework.DynamicFilters] New Feature - Add Linq/Lambda support (#7)

 

Yes, that works. That delegate is evaluated/executed to obtain the result so it can contain code and return a value.

**Comment by adrianotrentim** [comment] 2015-01-22 17:23
The error is in DynamicFilterExtension.cs, line 510. In this case, debugging I can see the variable startIdx with -1 value

 

Debugging, it generate this t-sql code

 

SELECT 

    [Var_1].[IdMenu] AS [IdMenu], 

    [Var_1].[Descricao] AS [Descricao], 

    [Var_1].[IdTipoMenu] AS [IdTipoMenu], 

    [Var_1].[Link] AS [Link], 

    [Var_1].[IdMenuSuperior] AS [IdMenuSuperior], 

    [Var_1].[Ordem] AS [Ordem], 

    [Var_1].[Ativo] AS [Ativo], 

    [Var_1].[SeparadorApos] AS [SeparadorApos], 

    [Var_1].[IdImagemMenu] AS [IdImagemMenu], 

    [Var_1].[IdImagemMenu16] AS [IdImagemMenu16]

    FROM [dbo].[Menu] AS [Var_1]

    WHERE 

                               ([Var_1].[IdMenu] in (

                                               @DynamicFilterParam_FilterMenu_values, 

                                               '3208eaf0-5b8a-e211-a120-00163ea5b928', 

                                               'a0d6ca1a-e58b-e211-a120-00163ea5b928', 

                                               '58fd6d5f-e58b-e211-a120-00163ea5b928', 

                                               '7b471832-ab8d-e211-a120-00163ea5b928', 

                                               '385d9d3b-ab8d-e211-a120-00163ea5b928', 

                                               'aa607a4b-ab8d-e211-a120-00163ea5b928', 

                                               'b9358955-8543-e211-be71-889ffa5dce70', 

                                               'ba358955-8543-e211-be71-889ffa5dce70', 

                                               'bb358955-8543-e211-be71-889ffa5dce70', 

                                               'bc358955-8543-e211-be71-889ffa5dce70', 

                                               'bd358955-8543-e211-be71-889ffa5dce70')

                               ) AND ([Var_1].[IdMenu] = @DynamicFilterParam_FilterMenu_values)

 

 

 


 


Adriano Trentim Augusto 






Diretor


Telefones: (16) 3011-3181 - (16) 99749-9099


E-mail:  <mailto:adriano@divsoft.com.br> adriano@divsoft.com.br


WebSite:  <http://www.divsoft.com.br/> http://www.divsoft.com.br/


 
 
 
 

 

De: jcachat [mailto:notifications@github.com] 
Enviada em: quarta-feira, 21 de janeiro de 2015 11:48
Para: jcachat/EntityFramework.DynamicFilters
Cc: adrianotrentim
Assunto: Re: [EntityFramework.DynamicFilters] New Feature - Add Linq/Lambda support (#7)

 

Yes, that works. That delegate is evaluated/executed to obtain the result so it can contain code and return a value.

**Comment by jcachat** [comment] 2015-01-22 17:30
You are defining your filter with a filter name of "GetType().Name".  Is it possible you are defining more than 1 filter with that same name?

From what you just posted, it looks like it correctly substituted all of the values.  But then there is ANOTHER instance of the parameter name "@DynamicFilterParam_FilterMenu_values" after the "in" clause.  So it looks like it's in there twice.

So when it's processing the 2nd parameter, it's finding the first instance of it, then trying to find the '=' before it and failing since it was already changed to "in".

If this is what's happening, I will need to add a check to throw an exception if a filter name is re-used.

**Comment by adrianotrentim** [comment] 2015-01-22 17:45
Hello,

 

considerations below

 

 

 


 


Adriano Trentim Augusto 






Diretor


Telefones: (16) 3011-3181 - (16) 99749-9099


E-mail:  <mailto:adriano@divsoft.com.br> adriano@divsoft.com.br


WebSite:  <http://www.divsoft.com.br/> http://www.divsoft.com.br/


 
 
 
 

 

De: jcachat [mailto:notifications@github.com] 
Enviada em: quinta-feira, 22 de janeiro de 2015 15:30
Para: jcachat/EntityFramework.DynamicFilters
Cc: adrianotrentim
Assunto: Re: [EntityFramework.DynamicFilters] New Feature - Add Linq/Lambda support (#7)

 

You are defining your filter with a filter name of "GetType().Name". Is it possible you are defining more than 1 filter with that same name?
I created a structure for each class that I need to put the filter, there is only one filter per class, if I need more filters I concatenate a '_blablabla ".

From what you just posted, it looks like it correctly substituted all of the values. But then there is ANOTHER instance of the parameter name "@DynamicFilterParam_FilterMenu_values" after the "in" clause. So it looks like it's in there twice.
Well, debugging realized he is actually calling the function twice. But there is only one filter and one called the entity. ReaderExecuting, on DynamicFilterCommandInterceptor.cs, line 23 is being called 2 times. Do not know why.

So when it's processing the 2nd parameter, it's finding the first instance of it, then trying to find the '=' before it and failing since it was already changed to "in".

If this is what's happening, I will need to add a check to throw an exception if a filter name is re-used.

**Comment by adrianotrentim** [comment] 2015-01-22 17:52
I noticed one thing, I do not know if it's relevant. I work with 2 DbContext identical, however accessing from 2 different databases. Every time he creates 2 DbContext, it sets the filters, but for each one of them. In this case it is possible that it is with the same name. You save the filter name by DbContext? or is one filter list for any application, such as static type?

 

 

 


 


Adriano Trentim Augusto 






Diretor


Telefones: (16) 3011-3181 - (16) 99749-9099


E-mail:  <mailto:adriano@divsoft.com.br> adriano@divsoft.com.br


WebSite:  <http://www.divsoft.com.br/> http://www.divsoft.com.br/


 
 
 
 

 

De: jcachat [mailto:notifications@github.com] 
Enviada em: quinta-feira, 22 de janeiro de 2015 15:30
Para: jcachat/EntityFramework.DynamicFilters
Cc: adrianotrentim
Assunto: Re: [EntityFramework.DynamicFilters] New Feature - Add Linq/Lambda support (#7)

 

You are defining your filter with a filter name of "GetType().Name". Is it possible you are defining more than 1 filter with that same name?

From what you just posted, it looks like it correctly substituted all of the values. But then there is ANOTHER instance of the parameter name "@DynamicFilterParam_FilterMenu_values" after the "in" clause. So it looks like it's in there twice.

So when it's processing the 2nd parameter, it's finding the first instance of it, then trying to find the '=' before it and failing since it was already changed to "in".

If this is what's happening, I will need to add a check to throw an exception if a filter name is re-used.

**Comment by jcachat** [comment] 2015-01-22 18:08
That may be the problem.  The filters are applied to the models inside EF - not to the DbContext.  But the queries are generated by EF and cached once.  I wonder if having 2 DbContexts to DIFFERENT databases is somehow causing me to pick up the filters twice when the queries are being cached.

If you can debug and step through the code, could you try setting a breakpoint on this line in both Visit() methods in DynamicFilterQueryVisitor?
```
var filterList = expression.Target.ElementType.MetadataProperties
                    .Where(mp => mp.Name.Contains("customannotation:" + DynamicFilterConstants.ATTRIBUTE_NAME_PREFIX))
                    .Select(m => m.Value as DynamicFilterDefinition);`
```

See if 2 items are in filterList.  There should only be 1.  But maybe EF is creating 1 for each database connection.

If that's it, it should be easy to correct.  You may even be able to just pop a Distinct() on there.

**Comment by adrianotrentim** [comment] 2015-01-22 18:13
That's it. when I create 2 DbContext it generates 2 times the same filter and if I get an error. But this filter should not be stored for each instance of DbContext?

 

When I created only one instance, it worked.

 

 


 


Adriano Trentim Augusto 






Diretor


Telefones: (16) 3011-3181 - (16) 99749-9099


E-mail:  <mailto:adriano@divsoft.com.br> adriano@divsoft.com.br


WebSite:  <http://www.divsoft.com.br/> http://www.divsoft.com.br/


 
 
 
 

 

De: jcachat [mailto:notifications@github.com] 
Enviada em: quinta-feira, 22 de janeiro de 2015 16:09
Para: jcachat/EntityFramework.DynamicFilters
Cc: adrianotrentim
Assunto: Re: [EntityFramework.DynamicFilters] New Feature - Add Linq/Lambda support (#7)

 

That may be the problem. The filters are applied to the models inside EF - not to the DbContext. But the queries are generated by EF and cached once. I wonder if having 2 DbContexts to DIFFERENT databases is somehow causing me to pick up the filters twice when the queries are being cached.

If you can debug and step through the code, could you try setting a breakpoint on this line in both Visit() methods in DynamicFilterQueryVisitor?

var filterList = expression.Target.ElementType.MetadataProperties
                    .Where(mp => mp.Name.Contains("customannotation:" + DynamicFilterConstants.ATTRIBUTE_NAME_PREFIX))
                    .Select(m => m.Value as DynamicFilterDefinition);`

See if 2 items are in filterList. There should only be 1. But maybe EF is creating 1 for each database connection.

If that's it, it should be easy to correct. You may even be able to just pop a Distinct() on there.

**Comment by adrianotrentim** [comment] 2015-01-22 18:17
There are 1 element at the filterList.

 

 

 

 

 


 


Adriano Trentim Augusto 






Diretor


Telefones: (16) 3011-3181 - (16) 99749-9099


E-mail:  <mailto:adriano@divsoft.com.br> adriano@divsoft.com.br


WebSite:  <http://www.divsoft.com.br/> http://www.divsoft.com.br/


 
 
 
 

 

De: jcachat [mailto:notifications@github.com] 
Enviada em: quinta-feira, 22 de janeiro de 2015 16:09
Para: jcachat/EntityFramework.DynamicFilters
Cc: adrianotrentim
Assunto: Re: [EntityFramework.DynamicFilters] New Feature - Add Linq/Lambda support (#7)

 

That may be the problem. The filters are applied to the models inside EF - not to the DbContext. But the queries are generated by EF and cached once. I wonder if having 2 DbContexts to DIFFERENT databases is somehow causing me to pick up the filters twice when the queries are being cached.

If you can debug and step through the code, could you try setting a breakpoint on this line in both Visit() methods in DynamicFilterQueryVisitor?

var filterList = expression.Target.ElementType.MetadataProperties
                    .Where(mp => mp.Name.Contains("customannotation:" + DynamicFilterConstants.ATTRIBUTE_NAME_PREFIX))
                    .Select(m => m.Value as DynamicFilterDefinition);`

See if 2 items are in filterList. There should only be 1. But maybe EF is creating 1 for each database connection.

If that's it, it should be easy to correct. You may even be able to just pop a Distinct() on there.

**Comment by adrianotrentim** [comment] 2015-01-22 18:18
Do you want to connect here with TeamViewer?

 

ID: 867 612 958

Pass: 6hgc31

 

 

 


 


Adriano Trentim Augusto 






Diretor


Telefones: (16) 3011-3181 - (16) 99749-9099


E-mail:  <mailto:adriano@divsoft.com.br> adriano@divsoft.com.br


WebSite:  <http://www.divsoft.com.br/> http://www.divsoft.com.br/


 
 
 
 

 

De: jcachat [mailto:notifications@github.com] 
Enviada em: quinta-feira, 22 de janeiro de 2015 16:09
Para: jcachat/EntityFramework.DynamicFilters
Cc: adrianotrentim
Assunto: Re: [EntityFramework.DynamicFilters] New Feature - Add Linq/Lambda support (#7)

 

That may be the problem. The filters are applied to the models inside EF - not to the DbContext. But the queries are generated by EF and cached once. I wonder if having 2 DbContexts to DIFFERENT databases is somehow causing me to pick up the filters twice when the queries are being cached.

If you can debug and step through the code, could you try setting a breakpoint on this line in both Visit() methods in DynamicFilterQueryVisitor?

var filterList = expression.Target.ElementType.MetadataProperties
                    .Where(mp => mp.Name.Contains("customannotation:" + DynamicFilterConstants.ATTRIBUTE_NAME_PREFIX))
                    .Select(m => m.Value as DynamicFilterDefinition);`

See if 2 items are in filterList. There should only be 1. But maybe EF is creating 1 for each database connection.

If that's it, it should be easy to correct. You may even be able to just pop a Distinct() on there.

**Comment by adrianotrentim** [comment] 2015-01-22 18:40
I have 2 databases, with the same structure and entities, but diferent databases connections: 

 

1nd with the generic informations, these informations are the same for all costumers.

2nd database, contains the informations for each specific costumer.

 

I need to create these 2 DbContext.

 

Some entities receive values from 1nd, Some entities from 2nd. But I keep the same structure and entities always.

 

You could simulate this case easily, creating 2 database with the same table, create one entity, and 2 DbContext, and apply the same filter for each one of the connections.

 

But if you prefer connecting here, feel free.

 

Att,

 

 


 


Adriano Trentim Augusto 






Diretor


Telefones: (16) 3011-3181 - (16) 99749-9099


E-mail:  <mailto:adriano@divsoft.com.br> adriano@divsoft.com.br


WebSite:  <http://www.divsoft.com.br/> http://www.divsoft.com.br/


 
 
 
 

 

De: jcachat [mailto:notifications@github.com] 
Enviada em: quinta-feira, 22 de janeiro de 2015 16:09
Para: jcachat/EntityFramework.DynamicFilters
Cc: adrianotrentim
Assunto: Re: [EntityFramework.DynamicFilters] New Feature - Add Linq/Lambda support (#7)

 

That may be the problem. The filters are applied to the models inside EF - not to the DbContext. But the queries are generated by EF and cached once. I wonder if having 2 DbContexts to DIFFERENT databases is somehow causing me to pick up the filters twice when the queries are being cached.

If you can debug and step through the code, could you try setting a breakpoint on this line in both Visit() methods in DynamicFilterQueryVisitor?

var filterList = expression.Target.ElementType.MetadataProperties
                    .Where(mp => mp.Name.Contains("customannotation:" + DynamicFilterConstants.ATTRIBUTE_NAME_PREFIX))
                    .Select(m => m.Value as DynamicFilterDefinition);`

See if 2 items are in filterList. There should only be 1. But maybe EF is creating 1 for each database connection.

If that's it, it should be easy to correct. You may even be able to just pop a Distinct() on there.

**Comment by jcachat** [comment] 2015-01-23 01:48
Found the problem and just pushed a fix.  NuGet has also been updated.

It was being caused by both DbContext's calling InitializeDynamicFilters().  That registers DynamicFilterInterceptor and DynamicFilterCommandInterceptor with EF.  Calling it twice was causing both of those classes to be called twice.  I've changed it to (statically) track if it's been initialized yet or not.  And in doing that, I was also able to remove having to manually call it at all.  Just calling Filter() will now do that for you the first time you call it.  So you can just remove the call to that method entirely (but it's still there and doesn't hurt to call it).

**Comment by adrianotrentim** [comment] 2015-01-23 12:36
John,

 

Perfect, I’ll try.

 

Att,

 

 

 

 


 


Adriano Trentim Augusto 






Diretor


Telefones: (16) 3011-3181 - (16) 99749-9099


E-mail:  <mailto:adriano@divsoft.com.br> adriano@divsoft.com.br


WebSite:  <http://www.divsoft.com.br/> http://www.divsoft.com.br/


 
 
 
 

 

De: jcachat [mailto:notifications@github.com] 
Enviada em: quinta-feira, 22 de janeiro de 2015 23:48
Para: jcachat/EntityFramework.DynamicFilters
Cc: Adriano Trentim
Assunto: Re: [EntityFramework.DynamicFilters] New Feature - Add Linq/Lambda support (#7)

 

Found the problem and just pushed a fix. NuGet has also been updated.

It was being caused by both DbContext's calling InitializeDynamicFilters(). That registers DynamicFilterInterceptor and DynamicFilterCommandInterceptor with EF. Calling it twice was causing both of those classes to be called twice. I've changed it to (statically) track if it's been initialized yet or not. And in doing that, I was also able to remove having to manually call it at all. Just calling Filter() will now do that for you the first time you call it. So you can just remove the call to that method entirely (but it's still there and doesn't hurt to call it).

**Comment by adrianotrentim** [comment] 2015-01-23 13:34
Hi John,

 

I had another idea (need) here. I need a condition for NavigationProperty, must reach a certain field in a parent table is equal "NNNNN" as in the example below:

 

modelBuilder.Filter(GetType().Name, (Menu query, List<Guid> values) =>

                query.IdTipoMenu == 0 ||

                query.Descricao == "XXX - SETRIN" ||

                query.MenuSuperior.Descricao == "XXX - SETRIN" ||

                values.Contains(query.IdMenu),

                () =>

                {

                    if (FilteredValues().Get<Guid>(GetType().Name) == null)

                    {

                        var modulosDisponiveis = new Repositorio<ModuloDisponivel>().ObjectSet.Where(t => t.Disponivel).Select(t => t.IdModulo).ToList();

                        var modulos = new Repositorio<ModuloItem>().ObjectSet.Where(m => modulosDisponiveis.Contains(m.IdModulo) && m.IdMenu != null).Select(t => (Guid)t.IdMenu).ToList();

 

                        FilteredValues().Set(GetType().Name, modulos.ToList());

                    }

 

                    return FilteredValues().Get<Guid>(GetType().Name);

                });

 

Any ideas to make an Inner Join automatically when the library to identify the property is a NavigationProperty?

 

Att,

 

 


 


Adriano Trentim Augusto 






Diretor


Telefones: (16) 3011-3181 - (16) 99749-9099


E-mail:  <mailto:adriano@divsoft.com.br> adriano@divsoft.com.br


WebSite:  <http://www.divsoft.com.br/> http://www.divsoft.com.br/


 
 
 
 

 

De: jcachat [mailto:notifications@github.com] 
Enviada em: quinta-feira, 22 de janeiro de 2015 23:48
Para: jcachat/EntityFramework.DynamicFilters
Cc: Adriano Trentim
Assunto: Re: [EntityFramework.DynamicFilters] New Feature - Add Linq/Lambda support (#7)

 

Found the problem and just pushed a fix. NuGet has also been updated.

It was being caused by both DbContext's calling InitializeDynamicFilters(). That registers DynamicFilterInterceptor and DynamicFilterCommandInterceptor with EF. Calling it twice was causing both of those classes to be called twice. I've changed it to (statically) track if it's been initialized yet or not. And in doing that, I was also able to remove having to manually call it at all. Just calling Filter() will now do that for you the first time you call it. So you can just remove the call to that method entirely (but it's still there and doesn't hurt to call it).

**Comment by jcachat** [comment] 2015-01-23 13:57
I've actually looked into that a little bit already but I didn't have any success.  Would you mind creating a new issue for that?  I'll make another attempt at it and see if it's possible.

**Comment by adrianotrentim** [comment] 2015-01-23 14:13
OK,

 

 

 


 


Adriano Trentim Augusto 






Diretor


Telefones: (16) 3011-3181 - (16) 99749-9099


E-mail:  <mailto:adriano@divsoft.com.br> adriano@divsoft.com.br


WebSite:  <http://www.divsoft.com.br/> http://www.divsoft.com.br/


 
 
 
 

 

De: jcachat [mailto:notifications@github.com] 
Enviada em: sexta-feira, 23 de janeiro de 2015 11:58
Para: jcachat/EntityFramework.DynamicFilters
Cc: Adriano Trentim
Assunto: Re: [EntityFramework.DynamicFilters] New Feature - Add Linq/Lambda support (#7)

 

I've actually looked into that a little bit already but I didn't have any success. Would you mind creating a new issue for that? I'll make another attempt at it and see if it's possible.

**Closed** 2015-02-14 19:27 UTC
