### ISSUE TITLE
SQL CE problem

### ISSUE THREAD

**Issue by hikalkan** [jcachat/EntityFramework.DynamicFilters#97] opened 2017-03-13 12:00 UTC
Hi,

When using with SQL CE, one of ABP's users getting this error: System.NotSupportedException: DesignTimeVisible
You can see details on: https://github.com/aspnetboilerplate/aspnetboilerplate/issues/981#issuecomment-284752596

Do you have an idea?
Thanks a lot.

**Comment by jcachat** [comment] 2017-03-17 16:49
It's because the CommandText property can't be changed in the CE driver.  And that is necessary in order to be able to inject parameter values for some types of filters.   The issue is also described by #16 and #81.

**Comment by jcachat** [comment] 2017-06-25 19:55
This was being caused by a change made for #53.  I just pushed a fix (NuGet package 2.8) that will prevent doing that for SQL CE (since that provider does not support modifying the CommandText).  Let me know how that works.

Also, Contains() using dynamic param values (i.e. an IEnumerable<T> parameter) is not supported for SQL CE because that also requires modifying the CommandText.  There is also a limitation on StartsWith.  I started a SQL CE limitations section in the readme.  See: https://github.com/jcachat/EntityFramework.DynamicFilters#sql-server-ce-support

**Closed** 2017-07-13 21:18 UTC
